"""initial

Revision ID: 49290dc57ed4
Revises: 
Create Date: 2021-03-14 11:54:41.932659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49290dc57ed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
