# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity_admin_user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='entity_admin_user.proto',
  package='entity',
  syntax='proto3',
  serialized_options=b'Z\002pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x65ntity_admin_user.proto\x12\x06\x65ntity\"4\n\tAdminUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x19\n\x0b\x41\x64minUserID\x12\n\n\x02id\x18\x01 \x01(\t\"9\n\x16\x43reateAdminUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x16UpdateAdminUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1c\n\x0b\x41\x63\x63\x65ssToken\x12\r\n\x05token\x18\x01 \x01(\t\"1\n\rAdminUserList\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.entity.AdminUserB\x04Z\x02pbb\x06proto3'
)




_ADMINUSER = _descriptor.Descriptor(
  name='AdminUser',
  full_name='entity.AdminUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='entity.AdminUser.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='entity.AdminUser.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='entity.AdminUser.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=87,
)


_ADMINUSERID = _descriptor.Descriptor(
  name='AdminUserID',
  full_name='entity.AdminUserID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='entity.AdminUserID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=114,
)


_CREATEADMINUSERREQUEST = _descriptor.Descriptor(
  name='CreateAdminUserRequest',
  full_name='entity.CreateAdminUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='entity.CreateAdminUserRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='entity.CreateAdminUserRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=173,
)


_UPDATEADMINUSERREQUEST = _descriptor.Descriptor(
  name='UpdateAdminUserRequest',
  full_name='entity.UpdateAdminUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='entity.UpdateAdminUserRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='entity.UpdateAdminUserRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=225,
)


_ACCESSTOKEN = _descriptor.Descriptor(
  name='AccessToken',
  full_name='entity.AccessToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='entity.AccessToken.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=255,
)


_ADMINUSERLIST = _descriptor.Descriptor(
  name='AdminUserList',
  full_name='entity.AdminUserList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='entity.AdminUserList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=306,
)

_ADMINUSERLIST.fields_by_name['items'].message_type = _ADMINUSER
DESCRIPTOR.message_types_by_name['AdminUser'] = _ADMINUSER
DESCRIPTOR.message_types_by_name['AdminUserID'] = _ADMINUSERID
DESCRIPTOR.message_types_by_name['CreateAdminUserRequest'] = _CREATEADMINUSERREQUEST
DESCRIPTOR.message_types_by_name['UpdateAdminUserRequest'] = _UPDATEADMINUSERREQUEST
DESCRIPTOR.message_types_by_name['AccessToken'] = _ACCESSTOKEN
DESCRIPTOR.message_types_by_name['AdminUserList'] = _ADMINUSERLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdminUser = _reflection.GeneratedProtocolMessageType('AdminUser', (_message.Message,), {
  'DESCRIPTOR' : _ADMINUSER,
  '__module__' : 'entity_admin_user_pb2'
  # @@protoc_insertion_point(class_scope:entity.AdminUser)
  })
_sym_db.RegisterMessage(AdminUser)

AdminUserID = _reflection.GeneratedProtocolMessageType('AdminUserID', (_message.Message,), {
  'DESCRIPTOR' : _ADMINUSERID,
  '__module__' : 'entity_admin_user_pb2'
  # @@protoc_insertion_point(class_scope:entity.AdminUserID)
  })
_sym_db.RegisterMessage(AdminUserID)

CreateAdminUserRequest = _reflection.GeneratedProtocolMessageType('CreateAdminUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEADMINUSERREQUEST,
  '__module__' : 'entity_admin_user_pb2'
  # @@protoc_insertion_point(class_scope:entity.CreateAdminUserRequest)
  })
_sym_db.RegisterMessage(CreateAdminUserRequest)

UpdateAdminUserRequest = _reflection.GeneratedProtocolMessageType('UpdateAdminUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEADMINUSERREQUEST,
  '__module__' : 'entity_admin_user_pb2'
  # @@protoc_insertion_point(class_scope:entity.UpdateAdminUserRequest)
  })
_sym_db.RegisterMessage(UpdateAdminUserRequest)

AccessToken = _reflection.GeneratedProtocolMessageType('AccessToken', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSTOKEN,
  '__module__' : 'entity_admin_user_pb2'
  # @@protoc_insertion_point(class_scope:entity.AccessToken)
  })
_sym_db.RegisterMessage(AccessToken)

AdminUserList = _reflection.GeneratedProtocolMessageType('AdminUserList', (_message.Message,), {
  'DESCRIPTOR' : _ADMINUSERLIST,
  '__module__' : 'entity_admin_user_pb2'
  # @@protoc_insertion_point(class_scope:entity.AdminUserList)
  })
_sym_db.RegisterMessage(AdminUserList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
