# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_article.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entity_article_pb2 as entity__article__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_article.proto',
  package='api',
  syntax='proto3',
  serialized_options=b'Z\002pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15service_article.proto\x12\x03\x61pi\x1a\x14\x65ntity_article.proto2\x87\x02\n\x0e\x41rticleService\x12)\n\x03Get\x12\x11.entity.ArticleID\x1a\x0f.entity.Article\x12,\n\x06GetAll\x12\r.entity.Pager\x1a\x13.entity.ArticleList\x12\x37\n\x06\x43reate\x12\x1c.entity.CreateArticleRequest\x1a\x0f.entity.Article\x12\x37\n\x06Update\x12\x1c.entity.UpdateArticleRequest\x1a\x0f.entity.Article\x12*\n\x06\x44\x65lete\x12\x11.entity.ArticleID\x1a\r.entity.EmptyB\x04Z\x02pbb\x06proto3'
  ,
  dependencies=[entity__article__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ARTICLESERVICE = _descriptor.ServiceDescriptor(
  name='ArticleService',
  full_name='api.ArticleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=53,
  serialized_end=316,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='api.ArticleService.Get',
    index=0,
    containing_service=None,
    input_type=entity__article__pb2._ARTICLEID,
    output_type=entity__article__pb2._ARTICLE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='api.ArticleService.GetAll',
    index=1,
    containing_service=None,
    input_type=entity__article__pb2._PAGER,
    output_type=entity__article__pb2._ARTICLELIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='api.ArticleService.Create',
    index=2,
    containing_service=None,
    input_type=entity__article__pb2._CREATEARTICLEREQUEST,
    output_type=entity__article__pb2._ARTICLE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='api.ArticleService.Update',
    index=3,
    containing_service=None,
    input_type=entity__article__pb2._UPDATEARTICLEREQUEST,
    output_type=entity__article__pb2._ARTICLE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='api.ArticleService.Delete',
    index=4,
    containing_service=None,
    input_type=entity__article__pb2._ARTICLEID,
    output_type=entity__article__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARTICLESERVICE)

DESCRIPTOR.services_by_name['ArticleService'] = _ARTICLESERVICE

# @@protoc_insertion_point(module_scope)
