# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: service_admin_user.proto

from google.protobuf import symbol_database as _symbol_database

from twirp.base import Endpoint
from twirp.server import TwirpServer
from twirp.client import TwirpClient

_sym_db = _symbol_database.Default()

class AdminUserServiceServer(TwirpServer):

	def __init__(self, *args, service, server_path_prefix="/twirp"):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/api.AdminUserService"
		self._endpoints = {
			"GetMe": Endpoint(
				service_name="AdminUserService",
				name="GetMe",
				function=getattr(service, "GetMe"),
				input=_sym_db.GetSymbol("entity.AdminUserID"),
				output=_sym_db.GetSymbol("entity.AdminUser"),
			),
			"Create": Endpoint(
				service_name="AdminUserService",
				name="Create",
				function=getattr(service, "Create"),
				input=_sym_db.GetSymbol("entity.CreateAdminUserRequest"),
				output=_sym_db.GetSymbol("entity.AdminUser"),
			),
			"Update": Endpoint(
				service_name="AdminUserService",
				name="Update",
				function=getattr(service, "Update"),
				input=_sym_db.GetSymbol("entity.UpdateAdminUserRequest"),
				output=_sym_db.GetSymbol("entity.AdminUser"),
			),
			"Delete": Endpoint(
				service_name="AdminUserService",
				name="Delete",
				function=getattr(service, "Delete"),
				input=_sym_db.GetSymbol("entity.AdminUserID"),
				output=_sym_db.GetSymbol("entity.Empty"),
			),
		}

class AdminUserServiceClient(TwirpClient):

	def GetMe(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/api.AdminUserService/GetMe",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("entity.AdminUser"),
			**kwargs,
		)

	def Create(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/api.AdminUserService/Create",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("entity.AdminUser"),
			**kwargs,
		)

	def Update(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/api.AdminUserService/Update",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("entity.AdminUser"),
			**kwargs,
		)

	def Delete(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/api.AdminUserService/Delete",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("entity.Empty"),
			**kwargs,
		)
