# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_admin_user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entity_article_pb2 as entity__article__pb2
import entity_admin_user_pb2 as entity__admin__user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_admin_user.proto',
  package='api',
  syntax='proto3',
  serialized_options=b'Z\002pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18service_admin_user.proto\x12\x03\x61pi\x1a\x14\x65ntity_article.proto\x1a\x17\x65ntity_admin_user.proto2\xed\x01\n\x10\x41\x64minUserService\x12\x31\n\x05GetMe\x12\x13.entity.AdminUserID\x1a\x11.entity.AdminUser\"\x00\x12;\n\x06\x43reate\x12\x1e.entity.CreateAdminUserRequest\x1a\x11.entity.AdminUser\x12;\n\x06Update\x12\x1e.entity.UpdateAdminUserRequest\x1a\x11.entity.AdminUser\x12,\n\x06\x44\x65lete\x12\x13.entity.AdminUserID\x1a\r.entity.EmptyB\x04Z\x02pbb\x06proto3'
  ,
  dependencies=[entity__article__pb2.DESCRIPTOR,entity__admin__user__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ADMINUSERSERVICE = _descriptor.ServiceDescriptor(
  name='AdminUserService',
  full_name='api.AdminUserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=81,
  serialized_end=318,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMe',
    full_name='api.AdminUserService.GetMe',
    index=0,
    containing_service=None,
    input_type=entity__admin__user__pb2._ADMINUSERID,
    output_type=entity__admin__user__pb2._ADMINUSER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='api.AdminUserService.Create',
    index=1,
    containing_service=None,
    input_type=entity__admin__user__pb2._CREATEADMINUSERREQUEST,
    output_type=entity__admin__user__pb2._ADMINUSER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='api.AdminUserService.Update',
    index=2,
    containing_service=None,
    input_type=entity__admin__user__pb2._UPDATEADMINUSERREQUEST,
    output_type=entity__admin__user__pb2._ADMINUSER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='api.AdminUserService.Delete',
    index=3,
    containing_service=None,
    input_type=entity__admin__user__pb2._ADMINUSERID,
    output_type=entity__article__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADMINUSERSERVICE)

DESCRIPTOR.services_by_name['AdminUserService'] = _ADMINUSERSERVICE

# @@protoc_insertion_point(module_scope)
